// Source taxonomies — the full genre/tag vocabularies the Discover builder offers
// for Royal Road and Scribble Hub. Harvested from each site's own search/list
// pages so the slugs match exactly. Each entry is { name, slug }; the builder
// stores a pick as { name, id: slug, kind: 'genre' | 'tag' } and the worker
// resolves the slug to the site's native filter (RR tagsAdd/tagsRemove;
// SH Series Finder genre ids / lazily-resolved tag ids).

export const ROYALROAD_GENRES = [
  { name: "Action", slug: "action" },
  { name: "Adventure", slug: "adventure" },
  { name: "Comedy", slug: "comedy" },
  { name: "Contemporary", slug: "contemporary" },
  { name: "Drama", slug: "drama" },
  { name: "Fantasy", slug: "fantasy" },
  { name: "Historical", slug: "historical" },
  { name: "Horror", slug: "horror" },
  { name: "Mystery", slug: "mystery" },
  { name: "Psychological", slug: "psychological" },
  { name: "Romance", slug: "romance_main" },
  { name: "Satire", slug: "satire" },
  { name: "Sci-fi", slug: "sci_fi" },
  { name: "Short Story", slug: "one_shot" },
  { name: "Thriller", slug: "thriller" },
  { name: "Tragedy", slug: "tragedy" },
];

export const ROYALROAD_TAGS = [
  { name: "Anti-Hero Lead", slug: "anti-hero_lead" },
  { name: "Anti-Villain Lead", slug: "antivillain_lead" },
  { name: "Apocalypse", slug: "apocalypse" },
  { name: "Artificial Intelligence", slug: "artificial_intelligence" },
  { name: "Attractive Lead", slug: "attractive_lead" },
  { name: "Chivalry", slug: "chivalry" },
  { name: "Competing Love Interest", slug: "competing_love" },
  { name: "Cozy", slug: "cozy" },
  { name: "Crafting", slug: "crafting" },
  { name: "Cultivation", slug: "cultivation" },
  { name: "Cyberpunk", slug: "cyberpunk" },
  { name: "Deck Building", slug: "deck_building" },
  { name: "Dungeon Core", slug: "dungeon_core" },
  { name: "Dungeon Crawler", slug: "dungeon_crawler" },
  { name: "Dystopia", slug: "dystopia" },
  { name: "Female Lead", slug: "female_lead" },
  { name: "First Contact", slug: "first_contact" },
  { name: "GameLit", slug: "gamelit" },
  { name: "Gender Bender", slug: "gender_bender" },
  { name: "Grimdark", slug: "grimdark" },
  { name: "Hard Sci-fi", slug: "hard_sci-fi" },
  { name: "High Fantasy", slug: "high_fantasy" },
  { name: "Kingdom Building", slug: "kingdom_building" },
  { name: "Lesbian Romance", slug: "lesbian_romance" },
  { name: "LitRPG", slug: "litrpg" },
  { name: "Local Protagonist", slug: "local_protagonist" },
  { name: "Low Fantasy", slug: "low_fantasy" },
  { name: "Magic", slug: "magic" },
  { name: "Magical Girl", slug: "magical_girl" },
  { name: "Magitech", slug: "magitech" },
  { name: "Male Gay Romance", slug: "gay_romance" },
  { name: "Male Lead", slug: "male_lead" },
  { name: "Martial Arts", slug: "martial_arts" },
  { name: "Mecha", slug: "mecha" },
  { name: "Modern Knowledge", slug: "modern_knowledge" },
  { name: "Monster Evolution", slug: "monster_evolution" },
  { name: "Multiple Lead Characters", slug: "multiple_lead" },
  { name: "Multiple Lovers", slug: "harem" },
  { name: "Mythos", slug: "mythos" },
  { name: "Non-Human Lead", slug: "non-human_lead" },
  { name: "Non-Humanoid Lead", slug: "nonhumanoid_lead" },
  { name: "Otome", slug: "otome" },
  { name: "Portal Fantasy / Isekai", slug: "summoned_hero" },
  { name: "Post Apocalyptic", slug: "post_apocalyptic" },
  { name: "Progression", slug: "progression" },
  { name: "Reader Interactive", slug: "reader_interactive" },
  { name: "Reincarnation", slug: "reincarnation" },
  { name: "Romance Subplot", slug: "romance" },
  { name: "Ruling Class", slug: "ruling_class" },
  { name: "School Life", slug: "school_life" },
  { name: "Secret Identity", slug: "secret_identity" },
  { name: "Slice of Life", slug: "slice_of_life" },
  { name: "Soft Sci-fi", slug: "soft_sci-fi" },
  { name: "Space Opera", slug: "space_opera" },
  { name: "Sports", slug: "sports" },
  { name: "Steampunk", slug: "steampunk" },
  { name: "Strategy", slug: "strategy" },
  { name: "Strong Lead", slug: "strong_lead" },
  { name: "Super Heroes", slug: "super_heroes" },
  { name: "Supernatural", slug: "supernatural" },
  { name: "Survival", slug: "survival" },
  { name: "System Invasion", slug: "system_invasion" },
  { name: "Technologically Engineered", slug: "technologically_engineered" },
  { name: "Time Loop", slug: "loop" },
  { name: "Time Travel", slug: "time_travel" },
  { name: "Tower", slug: "tower" },
  { name: "Urban Fantasy", slug: "urban_fantasy" },
  { name: "Villainous Lead", slug: "villainous_lead" },
  { name: "Virtual Reality", slug: "virtual_reality" },
  { name: "War and Military", slug: "war_and_military" },
  { name: "Wuxia", slug: "wuxia" },
];

export const SCRIBBLEHUB_GENRES = [
  { name: "Action", slug: "action" },
  { name: "Adult", slug: "adult" },
  { name: "Adventure", slug: "adventure" },
  { name: "Boys Love", slug: "boys-love" },
  { name: "Comedy", slug: "comedy" },
  { name: "Drama", slug: "drama" },
  { name: "Ecchi", slug: "ecchi" },
  { name: "Fanfiction", slug: "fanfiction" },
  { name: "Fantasy", slug: "fantasy" },
  { name: "Gender Bender", slug: "gender-bender" },
  { name: "Girls Love", slug: "girls-love" },
  { name: "Harem", slug: "harem" },
  { name: "Historical", slug: "historical" },
  { name: "Horror", slug: "horror" },
  { name: "Isekai", slug: "isekai" },
  { name: "Josei", slug: "josei" },
  { name: "LitRPG", slug: "litrpg" },
  { name: "Martial Arts", slug: "martial-arts" },
  { name: "Mature", slug: "mature" },
  { name: "Mecha", slug: "mecha" },
  { name: "Mystery", slug: "mystery" },
  { name: "Psychological", slug: "psychological" },
  { name: "Romance", slug: "romance" },
  { name: "School Life", slug: "school-life" },
  { name: "Sci-fi", slug: "sci-fi" },
  { name: "Seinen", slug: "seinen" },
  { name: "Slice of Life", slug: "slice-of-life" },
  { name: "Smut", slug: "smut" },
  { name: "Sports", slug: "sports" },
  { name: "Supernatural", slug: "supernatural" },
  { name: "Tragedy", slug: "tragedy" },
];

export const SCRIBBLEHUB_TAGS = [
  { name: "Abandoned Children", slug: "abandoned-children" },
  { name: "Ability Steal", slug: "ability-steal" },
  { name: "Absent Parents", slug: "absent-parents" },
  { name: "Abusive Characters", slug: "abusive-characters" },
  { name: "Academy", slug: "academy" },
  { name: "Accelerated Growth", slug: "accelerated-growth" },
  { name: "Acting", slug: "acting" },
  { name: "Adopted Children", slug: "adopted-children" },
  { name: "Adopted Protagonist", slug: "adopted-protagonist" },
  { name: "Adultery", slug: "adultery" },
  { name: "Adventurers", slug: "adventurers" },
  { name: "Affair", slug: "affair" },
  { name: "Age Progression", slug: "age-progression" },
  { name: "Age Regression", slug: "age-regression" },
  { name: "Aggressive Characters", slug: "aggressive-characters" },
  { name: "Alchemy", slug: "alchemy" },
  { name: "Aliens", slug: "aliens" },
  { name: "All-Girls School", slug: "all-girls-school" },
  { name: "Alternate World", slug: "alternate-world" },
  { name: "Amnesia", slug: "amnesia" },
  { name: "Amusement Park", slug: "amusement-park" },
  { name: "Ancient China", slug: "ancient-china" },
  { name: "Ancient Times", slug: "ancient-times" },
  { name: "Androgynous Characters", slug: "androgynous-characters" },
  { name: "Androids", slug: "androids" },
  { name: "Angels", slug: "angels" },
  { name: "Animal Characteristics", slug: "animal-characteristics" },
  { name: "Animal Rearing", slug: "animal-rearing" },
  { name: "Anti-Magic", slug: "anti-magic" },
  { name: "Anti-social Protagonist", slug: "anti-social-protagonist" },
  { name: "Antihero Protagonist", slug: "antihero-protagonist" },
  { name: "Antique Shop", slug: "antique-shop" },
  { name: "Apartment Life", slug: "apartment-life" },
  { name: "Apathetic Protagonist", slug: "apathetic-protagonist" },
  { name: "Apocalypse", slug: "apocalypse" },
  { name: "Appearance Changes", slug: "appearance-changes" },
  { name: "Appearance Different from Actual Age", slug: "appearance-different-from-actual-age" },
  { name: "Archery", slug: "archery" },
  { name: "Aristocracy", slug: "aristocracy" },
  { name: "Arms Dealers", slug: "arms-dealers" },
  { name: "Army", slug: "army" },
  { name: "Army Building", slug: "army-building" },
  { name: "Arranged Marriage", slug: "arranged-marriage" },
  { name: "Arrogant Characters", slug: "arrogant-characters" },
  { name: "Artifact Crafting", slug: "artifact-crafting" },
  { name: "Artifacts", slug: "artifacts" },
  { name: "Artificial Intelligence", slug: "artificial-intelligence" },
  { name: "Artists", slug: "artists" },
  { name: "Assassins", slug: "assassins" },
  { name: "Astrologers", slug: "astrologers" },
  { name: "Autism", slug: "autism" },
  { name: "Automatons", slug: "automatons" },
  { name: "Average-looking Protagonist", slug: "average-looking-protagonist" },
  { name: "Awkward Protagonist", slug: "awkward-protagonist" },
  { name: "Bands", slug: "bands" },
  { name: "Based on a Movie", slug: "based-on-a-movie" },
  { name: "Based on a Song", slug: "based-on-a-song" },
  { name: "Based on a Video Game", slug: "based-on-a-video-game" },
  { name: "Based on a Visual Novel", slug: "based-on-a-visual-novel" },
  { name: "Based on an Anime", slug: "based-on-an-anime" },
  { name: "Battle Academy", slug: "battle-academy" },
  { name: "Battle Competition", slug: "battle-competition" },
  { name: "BDSM", slug: "bdsm" },
  { name: "Beast Companions", slug: "beast-companions" },
  { name: "Beastkin", slug: "beastkin" },
  { name: "Beasts", slug: "beasts" },
  { name: "Beautiful Couple", slug: "beautiful-couple" },
  { name: "Beautiful Female Lead", slug: "beautiful-female-lead" },
  { name: "Betrayal", slug: "betrayal" },
  { name: "Bickering Couple", slug: "bickering-couple" },
  { name: "Biochip", slug: "biochip" },
  { name: "Biography", slug: "biography" },
  { name: "Bisexual Protagonist", slug: "bisexual-protagonist" },
  { name: "Black Belly", slug: "black-belly" },
  { name: "Blackmail", slug: "blackmail" },
  { name: "Blacksmith", slug: "blacksmith" },
  { name: "Blind Dates", slug: "blind-dates" },
  { name: "Blind Protagonist", slug: "blind-protagonist" },
  { name: "Blood Manipulation", slug: "blood-manipulation" },
  { name: "Bloodlines", slug: "bloodlines" },
  { name: "Body Swap", slug: "body-swap" },
  { name: "Body Tempering", slug: "body-tempering" },
  { name: "Body-double", slug: "body-double" },
  { name: "Bodyguards", slug: "bodyguards" },
  { name: "Books", slug: "books" },
  { name: "Bookworm", slug: "bookworm" },
  { name: "Boss-Subordinate Relationship", slug: "boss-subordinate-relationship" },
  { name: "Boy's Love Subplot", slug: "boys-love-subplot" },
  { name: "Brainwashing", slug: "brainwashing" },
  { name: "Broken Engagement", slug: "broken-engagement" },
  { name: "Brother Complex", slug: "brother-complex" },
  { name: "Brotherhood", slug: "brotherhood" },
  { name: "Buddhism", slug: "buddhism" },
  { name: "Bullying", slug: "bullying" },
  { name: "Business Management", slug: "business-management" },
  { name: "Businessmen", slug: "businessmen" },
  { name: "Butlers", slug: "butlers" },
  { name: "Calm Protagonist", slug: "calm-protagonist" },
  { name: "Cannibalism", slug: "cannibalism" },
  { name: "Card Games", slug: "card-games" },
  { name: "Carefree Protagonist", slug: "carefree-protagonist" },
  { name: "Caring Protagonist", slug: "caring-protagonist" },
  { name: "Cautious Protagonist", slug: "cautious-protagonist" },
  { name: "Celebrities", slug: "celebrities" },
  { name: "Character Growth", slug: "character-growth" },
  { name: "Charismatic Protagonist", slug: "charismatic-protagonist" },
  { name: "Charming Protagonist", slug: "charming-protagonist" },
  { name: "Chat Rooms", slug: "chat-rooms" },
  { name: "Cheating", slug: "cheating" },
  { name: "Cheats", slug: "cheats" },
  { name: "Chefs", slug: "chefs" },
  { name: "Child Abuse", slug: "child-abuse" },
  { name: "Child Protagonist", slug: "child-protagonist" },
  { name: "Childcare", slug: "childcare" },
  { name: "Childhood Friends", slug: "childhood-friends" },
  { name: "Childhood Love", slug: "childhood-love" },
  { name: "Childhood Promise", slug: "childhood-promise" },
  { name: "Childish Protagonist", slug: "childish-protagonist" },
  { name: "Chuunibyou", slug: "chuunibyou" },
  { name: "Clan Building", slug: "clan-building" },
  { name: "Classic", slug: "classic" },
  { name: "Clever Protagonist", slug: "clever-protagonist" },
  { name: "Clingy Lover", slug: "clingy-lover" },
  { name: "Clones", slug: "clones" },
  { name: "Clubs", slug: "clubs" },
  { name: "Clumsy Love Interests", slug: "clumsy-love-interests" },
  { name: "Co-Workers", slug: "co-workers" },
  { name: "Cohabitation", slug: "cohabitation" },
  { name: "Cold Love Interests", slug: "cold-love-interests" },
  { name: "Cold Protagonist", slug: "cold-protagonist" },
  { name: "Collection of Short Stories", slug: "collection-of-short-stories" },
  { name: "College/University", slug: "college-university" },
  { name: "Coma", slug: "coma" },
  { name: "Comedic Undertone", slug: "comedic-undertone" },
  { name: "Coming of Age", slug: "coming-of-age" },
  { name: "Complex Family Relationships", slug: "complex-family-relationships" },
  { name: "Conditional Power", slug: "conditional-power" },
  { name: "Confident Protagonist", slug: "confident-protagonist" },
  { name: "Confinement", slug: "confinement" },
  { name: "Conflicting Loyalties", slug: "conflicting-loyalties" },
  { name: "Conspiracies", slug: "conspiracies" },
  { name: "Contracts", slug: "contracts" },
  { name: "Cooking", slug: "cooking" },
  { name: "Corruption", slug: "corruption" },
  { name: "Cosmic Wars", slug: "cosmic-wars" },
  { name: "Cosplay", slug: "cosplay" },
  { name: "Couple Growth", slug: "couple-growth" },
  { name: "Court Official", slug: "court-official" },
  { name: "Cousins", slug: "cousins" },
  { name: "Cowardly Protagonist", slug: "cowardly-protagonist" },
  { name: "Crafting", slug: "crafting" },
  { name: "Crazy Protagonist", slug: "crazy-protagonist" },
  { name: "Crime", slug: "crime" },
  { name: "Criminals", slug: "criminals" },
  { name: "Cross-dressing", slug: "cross-dressing" },
  { name: "Crossover", slug: "crossover" },
  { name: "Cruel Characters", slug: "cruel-characters" },
  { name: "Cryostasis", slug: "cryostasis" },
  { name: "Cultivation", slug: "cultivation" },
  { name: "Cunning Protagonist", slug: "cunning-protagonist" },
  { name: "Curious Protagonist", slug: "curious-protagonist" },
  { name: "Curses", slug: "curses" },
  { name: "Cute Children", slug: "cute-children" },
  { name: "Cute Protagonist", slug: "cute-protagonist" },
  { name: "Cute Story", slug: "cute-story" },
  { name: "Cyberpunk", slug: "cyberpunk" },
  { name: "Dancers", slug: "dancers" },
  { name: "Dao Companion", slug: "dao-companion" },
  { name: "Dao Comprehension", slug: "dao-comprehension" },
  { name: "Daoism", slug: "daoism" },
  { name: "Dark", slug: "dark" },
  { name: "Dead Protagonist", slug: "dead-protagonist" },
  { name: "Death", slug: "death" },
  { name: "Death of Loved Ones", slug: "death-of-loved-ones" },
  { name: "Debts", slug: "debts" },
  { name: "Delinquents", slug: "delinquents" },
  { name: "Delusions", slug: "delusions" },
  { name: "Demi-Humans", slug: "demi-humans" },
  { name: "Demon Lord", slug: "demon-lord" },
  { name: "Demonic Cultivation Technique", slug: "demonic-cultivation-technique" },
  { name: "Demons", slug: "demons" },
  { name: "Dense Protagonist", slug: "dense-protagonist" },
  { name: "Depictions of Cruelty", slug: "depictions-of-cruelty" },
  { name: "Depression", slug: "depression" },
  { name: "Destiny", slug: "destiny" },
  { name: "Detectives", slug: "detectives" },
  { name: "Determined Protagonist", slug: "determined-protagonist" },
  { name: "Devoted Love Interests", slug: "devoted-love-interests" },
  { name: "Different Social Status", slug: "different-social-status" },
  { name: "Disabilities", slug: "disabilities" },
  { name: "Discrimination", slug: "discrimination" },
  { name: "Disfigurement", slug: "disfigurement" },
  { name: "Dishonest Protagonist", slug: "dishonest-protagonist" },
  { name: "Distrustful Protagonist", slug: "distrustful-protagonist" },
  { name: "Divination", slug: "divination" },
  { name: "Divine Protection", slug: "divine-protection" },
  { name: "Divorce", slug: "divorce" },
  { name: "Doctors", slug: "doctors" },
  { name: "Dolls/Puppets", slug: "dolls-puppets" },
  { name: "Domestic Affairs", slug: "domestic-affairs" },
  { name: "Doting Love Interests", slug: "doting-love-interests" },
  { name: "Doting Older Siblings", slug: "doting-older-siblings" },
  { name: "Doting Parents", slug: "doting-parents" },
  { name: "Dragon Riders", slug: "dragon-riders" },
  { name: "Dragon Slayers", slug: "dragon-slayers" },
  { name: "Dragons", slug: "dragons" },
  { name: "Dreams", slug: "dreams" },
  { name: "Drugs", slug: "drugs" },
  { name: "Druids", slug: "druids" },
  { name: "Dungeon Master", slug: "dungeon-master" },
  { name: "Dungeons", slug: "dungeons" },
  { name: "Dwarfs", slug: "dwarfs" },
  { name: "Dystopia", slug: "dystopia" },
  { name: "e-Sports", slug: "e-sports" },
  { name: "Early Romance", slug: "early-romance" },
  { name: "Earth Invasion", slug: "earth-invasion" },
  { name: "Easy Going Life", slug: "easy-going-life" },
  { name: "Economics", slug: "economics" },
  { name: "Editors", slug: "editors" },
  { name: "Eidetic Memory", slug: "eidetic-memory" },
  { name: "Elderly Protagonist", slug: "elderly-protagonist" },
  { name: "Elemental Magic", slug: "elemental-magic" },
  { name: "Elves", slug: "elves" },
  { name: "Emotionally Weak Protagonist", slug: "emotionally-weak-protagonist" },
  { name: "Empires", slug: "empires" },
  { name: "Enemies Become Allies", slug: "enemies-become-allies" },
  { name: "Enemies Become Lovers", slug: "enemies-become-lovers" },
  { name: "Engagement", slug: "engagement" },
  { name: "Engineer", slug: "engineer" },
  { name: "Enlightenment", slug: "enlightenment" },
  { name: "Episodic", slug: "episodic" },
  { name: "Eunuch", slug: "eunuch" },
  { name: "European Ambience", slug: "european-ambience" },
  { name: "Evil Gods", slug: "evil-gods" },
  { name: "Evil Organizations", slug: "evil-organizations" },
  { name: "Evil Protagonist", slug: "evil-protagonist" },
  { name: "Evil Religions", slug: "evil-religions" },
  { name: "Evolution", slug: "evolution" },
  { name: "Exhibitionism", slug: "exhibitionism" },
  { name: "Exorcism", slug: "exorcism" },
  { name: "Eye Powers", slug: "eye-powers" },
  { name: "Fairies", slug: "fairies" },
  { name: "Fallen Angels", slug: "fallen-angels" },
  { name: "Fallen Nobility", slug: "fallen-nobility" },
  { name: "Familial Love", slug: "familial-love" },
  { name: "Familiars", slug: "familiars" },
  { name: "Family", slug: "family" },
  { name: "Family Business", slug: "family-business" },
  { name: "Family Conflict", slug: "family-conflict" },
  { name: "Famous Parents", slug: "famous-parents" },
  { name: "Famous Protagonist", slug: "famous-protagonist" },
  { name: "Fanaticism", slug: "fanaticism" },
  { name: "Fantasy Creatures", slug: "fantasy-creatures" },
  { name: "Fantasy World", slug: "fantasy-world" },
  { name: "Farming", slug: "farming" },
  { name: "Fast Cultivation", slug: "fast-cultivation" },
  { name: "Fast Learner", slug: "fast-learner" },
  { name: "Fat Protagonist", slug: "fat-protagonist" },
  { name: "Fat to Fit", slug: "fat-to-fit" },
  { name: "Fated Lovers", slug: "fated-lovers" },
  { name: "Fearless Protagonist", slug: "fearless-protagonist" },
  { name: "Female Master", slug: "female-master" },
  { name: "Female Protagonist", slug: "female-protagonist" },
  { name: "Female to Male", slug: "female-to-male" },
  { name: "Feng Shui", slug: "feng-shui" },
  { name: "Firearms", slug: "firearms" },
  { name: "First Love", slug: "first-love" },
  { name: "First-time Intercourse", slug: "first-time-intercourse" },
  { name: "Flashbacks", slug: "flashbacks" },
  { name: "Fleet Battles", slug: "fleet-battles" },
  { name: "Folklore", slug: "folklore" },
  { name: "Forced into a Relationship", slug: "forced-into-a-relationship" },
  { name: "Forced Living Arrangements", slug: "forced-living-arrangements" },
  { name: "Forced Marriage", slug: "forced-marriage" },
  { name: "Forgetful Protagonist", slug: "forgetful-protagonist" },
  { name: "Former Hero", slug: "former-hero" },
  { name: "Fourth Wall", slug: "fourth-wall" },
  { name: "Fox Spirits", slug: "fox-spirits" },
  { name: "Friends Become Enemies", slug: "friends-become-enemies" },
  { name: "Friendship", slug: "friendship" },
  { name: "Fujoshi", slug: "fujoshi" },
  { name: "Futanari", slug: "futanari" },
  { name: "Futuristic Setting", slug: "futuristic-setting" },
  { name: "Galge", slug: "galge" },
  { name: "Gambling", slug: "gambling" },
  { name: "Game Elements", slug: "game-elements" },
  { name: "Game Ranking System", slug: "game-ranking-system" },
  { name: "Gamers", slug: "gamers" },
  { name: "Gangs", slug: "gangs" },
  { name: "Gate to Another World", slug: "gate-to-another-world" },
  { name: "Genderless Protagonist", slug: "genderless-protagonist" },
  { name: "Generals", slug: "generals" },
  { name: "Genetic Modifications", slug: "genetic-modifications" },
  { name: "Genies", slug: "genies" },
  { name: "Genius Protagonist", slug: "genius-protagonist" },
  { name: "Ghosts", slug: "ghosts" },
  { name: "Girl's Love Subplot", slug: "girls-love-subplot" },
  { name: "Gladiators", slug: "gladiators" },
  { name: "Glasses-wearing Love Interests", slug: "glasses-wearing-love-interests" },
  { name: "Glasses-wearing Protagonist", slug: "glasses-wearing-protagonist" },
  { name: "Goblins", slug: "goblins" },
  { name: "God Protagonist", slug: "god-protagonist" },
  { name: "God-human Relationship", slug: "god-human-relationship" },
  { name: "Goddesses", slug: "goddesses" },
  { name: "Godly Powers", slug: "godly-powers" },
  { name: "Gods", slug: "gods" },
  { name: "Golems", slug: "golems" },
  { name: "Gore", slug: "gore" },
  { name: "Grave Keepers", slug: "grave-keepers" },
  { name: "Grinding", slug: "grinding" },
  { name: "Guardian Relationship", slug: "guardian-relationship" },
  { name: "Guilds", slug: "guilds" },
  { name: "Gunfighters", slug: "gunfighters" },
  { name: "Hackers", slug: "hackers" },
  { name: "Half-human Protagonist", slug: "half-human-protagonist" },
  { name: "Handjob", slug: "handjob" },
  { name: "Handsome Male Lead", slug: "handsome-male-lead" },
  { name: "Hard-Working Protagonist", slug: "hard-working-protagonist" },
  { name: "Harem-seeking Protagonist", slug: "harem-seeking-protagonist" },
  { name: "Harsh Training", slug: "harsh-training" },
  { name: "Hated Protagonist", slug: "hated-protagonist" },
  { name: "Healers", slug: "healers" },
  { name: "Healing", slug: "healing" },
  { name: "Heartwarming", slug: "heartwarming" },
  { name: "Heaven", slug: "heaven" },
  { name: "Heavenly Tribulation", slug: "heavenly-tribulation" },
  { name: "Hell", slug: "hell" },
  { name: "Helpful Protagonist", slug: "helpful-protagonist" },
  { name: "Herbalist", slug: "herbalist" },
  { name: "Heroes", slug: "heroes" },
  { name: "Heterochromia", slug: "heterochromia" },
  { name: "Hidden Abilities", slug: "hidden-abilities" },
  { name: "Hiding True Abilities", slug: "hiding-true-abilities" },
  { name: "Hiding True Identity", slug: "hiding-true-identity" },
  { name: "Hikikomori", slug: "hikikomori" },
  { name: "Homunculus", slug: "homunculus" },
  { name: "Honest Protagonist", slug: "honest-protagonist" },
  { name: "Hospital", slug: "hospital" },
  { name: "Hot-blooded Protagonist", slug: "hot-blooded-protagonist" },
  { name: "Human Experimentation", slug: "human-experimentation" },
  { name: "Human Weapon", slug: "human-weapon" },
  { name: "Human-Nonhuman Relationship", slug: "human-nonhuman-relationship" },
  { name: "Humanoid Protagonist", slug: "humanoid-protagonist" },
  { name: "Hunters", slug: "hunters" },
  { name: "Hypnotism", slug: "hypnotism" },
  { name: "Identity Crisis", slug: "identity-crisis" },
  { name: "Imaginary Friend", slug: "imaginary-friend" },
  { name: "Immortals", slug: "immortals" },
  { name: "Imperial Harem", slug: "imperial-harem" },
  { name: "Incest", slug: "incest" },
  { name: "Incubus", slug: "incubus" },
  { name: "Indecisive Protagonist", slug: "indecisive-protagonist" },
  { name: "Industrialization", slug: "industrialization" },
  { name: "Inferiority Complex", slug: "inferiority-complex" },
  { name: "Inheritance", slug: "inheritance" },
  { name: "Inscriptions", slug: "inscriptions" },
  { name: "Insects", slug: "insects" },
  { name: "Interconnected Storylines", slug: "interconnected-storylines" },
  { name: "Interdimensional Travel", slug: "interdimensional-travel" },
  { name: "Introverted Protagonist", slug: "introverted-protagonist" },
  { name: "Investigations", slug: "investigations" },
  { name: "Invisibility", slug: "invisibility" },
  { name: "Jack of All Trades", slug: "jack-of-all-trades" },
  { name: "Jealousy", slug: "jealousy" },
  { name: "Jiangshi", slug: "jiangshi" },
  { name: "Jobless Class", slug: "jobless-class" },
  { name: "Kidnappings", slug: "kidnappings" },
  { name: "Kind Love Interests", slug: "kind-love-interests" },
  { name: "Kingdom Building", slug: "kingdom-building" },
  { name: "Kingdoms", slug: "kingdoms" },
  { name: "Knights", slug: "knights" },
  { name: "Kuudere", slug: "kuudere" },
  { name: "Lack of Common Sense", slug: "lack-of-common-sense" },
  { name: "Language Barrier", slug: "language-barrier" },
  { name: "Late Romance", slug: "late-romance" },
  { name: "Lawyers", slug: "lawyers" },
  { name: "Lazy Protagonist", slug: "lazy-protagonist" },
  { name: "Leadership", slug: "leadership" },
  { name: "Legends", slug: "legends" },
  { name: "Level System", slug: "level-system" },
  { name: "Library", slug: "library" },
  { name: "Limited Lifespan", slug: "limited-lifespan" },
  { name: "Living Abroad", slug: "living-abroad" },
  { name: "Living Alone", slug: "living-alone" },
  { name: "Loli", slug: "loli" },
  { name: "Loneliness", slug: "loneliness" },
  { name: "Loner Protagonist", slug: "loner-protagonist" },
  { name: "Long Separations", slug: "long-separations" },
  { name: "Long-distance Relationship", slug: "long-distance-relationship" },
  { name: "Lost Civilizations", slug: "lost-civilizations" },
  { name: "Lottery", slug: "lottery" },
  { name: "Love at First Sight", slug: "love-at-first-sight" },
  { name: "Love Interest Falls in Love First", slug: "love-interest-falls-in-love-first" },
  { name: "Love Rivals", slug: "love-rivals" },
  { name: "Love Triangles", slug: "love-triangles" },
  { name: "Lovers Reunited", slug: "lovers-reunited" },
  { name: "Low-key Protagonist", slug: "low-key-protagonist" },
  { name: "Loyal Subordinates", slug: "loyal-subordinates" },
  { name: "Lucky Protagonist", slug: "lucky-protagonist" },
  { name: "Magic", slug: "magic" },
  { name: "Magic Beasts", slug: "magic-beasts" },
  { name: "Magic Formations", slug: "magic-formations" },
  { name: "Magical Girls", slug: "magical-girls" },
  { name: "Magical Space", slug: "magical-space" },
  { name: "Magical Technology", slug: "magical-technology" },
  { name: "Maids", slug: "maids" },
  { name: "Male Protagonist", slug: "male-protagonist" },
  { name: "Male to Female", slug: "male-to-female" },
  { name: "Male Yandere", slug: "male-yandere" },
  { name: "Management", slug: "management" },
  { name: "Mangaka", slug: "mangaka" },
  { name: "Manipulative Characters", slug: "manipulative-characters" },
  { name: "Manly Gay Couple", slug: "manly-gay-couple" },
  { name: "Marriage", slug: "marriage" },
  { name: "Marriage of Convenience", slug: "marriage-of-convenience" },
  { name: "Martial Spirits", slug: "martial-spirits" },
  { name: "Masochistic Characters", slug: "masochistic-characters" },
  { name: "Master-Disciple Relationship", slug: "master-disciple-relationship" },
  { name: "Master-Servant Relationship", slug: "master-servant-relationship" },
  { name: "Masturbation", slug: "masturbation" },
  { name: "Matriarchy", slug: "matriarchy" },
  { name: "Mature Protagonist", slug: "mature-protagonist" },
  { name: "Medical Knowledge", slug: "medical-knowledge" },
  { name: "Medieval", slug: "medieval" },
  { name: "Mercenaries", slug: "mercenaries" },
  { name: "Merchants", slug: "merchants" },
  { name: "Military", slug: "military" },
  { name: "Mind Break", slug: "mind-break" },
  { name: "Mind Control", slug: "mind-control" },
  { name: "Misandry", slug: "misandry" },
  { name: "Mismatched Couple", slug: "mismatched-couple" },
  { name: "Misunderstandings", slug: "misunderstandings" },
  { name: "MMORPG", slug: "mmorpg" },
  { name: "Mob Protagonist", slug: "mob-protagonist" },
  { name: "Models", slug: "models" },
  { name: "Modern Day", slug: "modern-day" },
  { name: "Modern Fantasy", slug: "modern-fantasy" },
  { name: "Modern Knowledge", slug: "modern-knowledge" },
  { name: "Modern Time", slug: "modern-time" },
  { name: "Money Grubber", slug: "money-grubber" },
  { name: "Monster Girls", slug: "monster-girls" },
  { name: "Monster Society", slug: "monster-society" },
  { name: "Monster Tamer", slug: "monster-tamer" },
  { name: "Monsters", slug: "monsters" },
  { name: "Movies", slug: "movies" },
  { name: "Mpreg", slug: "mpreg" },
  { name: "Multiple Identities", slug: "multiple-identities" },
  { name: "Multiple Personalities", slug: "multiple-personalities" },
  { name: "Multiple POV", slug: "multiple-pov" },
  { name: "Multiple Protagonists", slug: "multiple-protagonists" },
  { name: "Multiple Realms", slug: "multiple-realms" },
  { name: "Multiple Reincarnated Individuals", slug: "multiple-reincarnated-individuals" },
  { name: "Multiple Timelines", slug: "multiple-timelines" },
  { name: "Multiple Transported Individuals", slug: "multiple-transported-individuals" },
  { name: "Murders", slug: "murders" },
  { name: "Music", slug: "music" },
  { name: "Mutated Creatures", slug: "mutated-creatures" },
  { name: "Mutations", slug: "mutations" },
  { name: "Mute Character", slug: "mute-character" },
  { name: "Mysterious Family Background", slug: "mysterious-family-background" },
  { name: "Mysterious Illness", slug: "mysterious-illness" },
  { name: "Mysterious Past", slug: "mysterious-past" },
  { name: "Mystery Solving", slug: "mystery-solving" },
  { name: "Mythical Beasts", slug: "mythical-beasts" },
  { name: "Mythology", slug: "mythology" },
  { name: "Naive Protagonist", slug: "naive-protagonist" },
  { name: "Narcissistic Protagonist", slug: "narcissistic-protagonist" },
  { name: "Nationalism", slug: "nationalism" },
  { name: "Near-Death Experience", slug: "near-death-experience" },
  { name: "Necromancer", slug: "necromancer" },
  { name: "Neet", slug: "neet" },
  { name: "Netorare", slug: "netorare" },
  { name: "Netorase", slug: "netorase" },
  { name: "Netori", slug: "netori" },
  { name: "Nightmares", slug: "nightmares" },
  { name: "Ninjas", slug: "ninjas" },
  { name: "Nobles", slug: "nobles" },
  { name: "Non-human Protagonist", slug: "non-human-protagonist" },
  { name: "Non-humanoid Protagonist", slug: "non-humanoid-protagonist" },
  { name: "Non-linear Storytelling", slug: "non-linear-storytelling" },
  { name: "Nudity", slug: "nudity" },
  { name: "Nurses", slug: "nurses" },
  { name: "Obsessive Love", slug: "obsessive-love" },
  { name: "Office Romance", slug: "office-romance" },
  { name: "Older Love Interests", slug: "older-love-interests" },
  { name: "Omegaverse", slug: "omegaverse" },
  { name: "Oneshot", slug: "oneshot" },
  { name: "Online Romance", slug: "online-romance" },
  { name: "Onmyouji", slug: "onmyouji" },
  { name: "Orcs", slug: "orcs" },
  { name: "Organized Crime", slug: "organized-crime" },
  { name: "Orphans", slug: "orphans" },
  { name: "Otaku", slug: "otaku" },
  { name: "Otome Game", slug: "otome-game" },
  { name: "Outcasts", slug: "outcasts" },
  { name: "Outdoor Intercourse", slug: "outdoor-intercourse" },
  { name: "Outer Space", slug: "outer-space" },
  { name: "Overpowered Protagonist", slug: "overpowered-protagonist" },
  { name: "Overprotective Siblings", slug: "overprotective-siblings" },
  { name: "Pacifist Protagonist", slug: "pacifist-protagonist" },
  { name: "Paizuri", slug: "paizuri" },
  { name: "Pansexual Protagonist", slug: "pansexual-protagonist" },
  { name: "Parallel Worlds", slug: "parallel-worlds" },
  { name: "Parasites", slug: "parasites" },
  { name: "Parent Complex", slug: "parent-complex" },
  { name: "Parody", slug: "parody" },
  { name: "Part-Time Job", slug: "part-time-job" },
  { name: "Past Plays a Big Role", slug: "past-plays-a-big-role" },
  { name: "Past Trauma", slug: "past-trauma" },
  { name: "Persistent Love Interests", slug: "persistent-love-interests" },
  { name: "Personality Changes", slug: "personality-changes" },
  { name: "Perverted Protagonist", slug: "perverted-protagonist" },
  { name: "Pets", slug: "pets" },
  { name: "Pharmacist", slug: "pharmacist" },
  { name: "Philosophical", slug: "philosophical" },
  { name: "Phobias", slug: "phobias" },
  { name: "Phoenixes", slug: "phoenixes" },
  { name: "Photography", slug: "photography" },
  { name: "Pill Based Cultivation", slug: "pill-based-cultivation" },
  { name: "Pill Concocting", slug: "pill-concocting" },
  { name: "Pilots", slug: "pilots" },
  { name: "Pirates", slug: "pirates" },
  { name: "Playboys", slug: "playboys" },
  { name: "Playful Protagonist", slug: "playful-protagonist" },
  { name: "Poetry", slug: "poetry" },
  { name: "Poisons", slug: "poisons" },
  { name: "Police", slug: "police" },
  { name: "Polite Protagonist", slug: "polite-protagonist" },
  { name: "Politics", slug: "politics" },
  { name: "Polyandry", slug: "polyandry" },
  { name: "Polygamy", slug: "polygamy" },
  { name: "Poor Protagonist", slug: "poor-protagonist" },
  { name: "Poor to Rich", slug: "poor-to-rich" },
  { name: "Popular Love Interests", slug: "popular-love-interests" },
  { name: "Possession", slug: "possession" },
  { name: "Possessive Characters", slug: "possessive-characters" },
  { name: "Post-apocalyptic", slug: "post-apocalyptic" },
  { name: "Power Couple", slug: "power-couple" },
  { name: "Power Struggle", slug: "power-struggle" },
  { name: "Pragmatic Protagonist", slug: "pragmatic-protagonist" },
  { name: "Precognition", slug: "precognition" },
  { name: "Pregnancy", slug: "pregnancy" },
  { name: "Pretend Lovers", slug: "pretend-lovers" },
  { name: "Previous Life Talent", slug: "previous-life-talent" },
  { name: "Priestesses", slug: "priestesses" },
  { name: "Priests", slug: "priests" },
  { name: "Prison", slug: "prison" },
  { name: "Proactive Protagonist", slug: "proactive-protagonist" },
  { name: "Programmer", slug: "programmer" },
  { name: "Prophecies", slug: "prophecies" },
  { name: "Prostitutes", slug: "prostitutes" },
  { name: "Protagonist Falls in Love First", slug: "protagonist-falls-in-love-first" },
  { name: "Protagonist Loyal to Love Interest", slug: "protagonist-loyal-to-love-interest" },
  { name: "Protagonist Strong from the Start", slug: "protagonist-strong-from-the-start" },
  { name: "Protagonist with Multiple Bodies", slug: "protagonist-with-multiple-bodies" },
  { name: "Psychic Powers", slug: "psychic-powers" },
  { name: "Psychopaths", slug: "psychopaths" },
  { name: "Puppeteers", slug: "puppeteers" },
  { name: "Quiet Characters", slug: "quiet-characters" },
  { name: "Quirky Characters", slug: "quirky-characters" },
  { name: "R-15", slug: "r-15" },
  { name: "R-18", slug: "r-18" },
  { name: "Race Change", slug: "race-change" },
  { name: "Racism", slug: "racism" },
  { name: "Rape", slug: "rape" },
  { name: "Rebellion", slug: "rebellion" },
  { name: "Reincarnated as a Monster", slug: "reincarnated-as-a-monster" },
  { name: "Reincarnated as an Object", slug: "reincarnated-as-an-object" },
  { name: "Reincarnated into a Game World", slug: "reincarnated-into-a-game-world" },
  { name: "Reincarnated into Another World", slug: "reincarnated-into-another-world" },
  { name: "Reincarnation", slug: "reincarnation" },
  { name: "Religions", slug: "religions" },
  { name: "Reluctant Protagonist", slug: "reluctant-protagonist" },
  { name: "Reporters", slug: "reporters" },
  { name: "Restaurant", slug: "restaurant" },
  { name: "Resurrection", slug: "resurrection" },
  { name: "Returning from Another World", slug: "returning-from-another-world" },
  { name: "Revenge", slug: "revenge" },
  { name: "Reverse Harem", slug: "reverse-harem" },
  { name: "Reverse Rape", slug: "reverse-rape" },
  { name: "Rich to Poor", slug: "rich-to-poor" },
  { name: "Righteous Protagonist", slug: "righteous-protagonist" },
  { name: "Rivalry", slug: "rivalry" },
  { name: "Romantic Subplot", slug: "romantic-subplot" },
  { name: "Roommates", slug: "roommates" },
  { name: "Royalty", slug: "royalty" },
  { name: "RPG", slug: "rpg" },
  { name: "Ruthless Protagonist", slug: "ruthless-protagonist" },
  { name: "Sadistic Characters", slug: "sadistic-characters" },
  { name: "Saints", slug: "saints" },
  { name: "Salaryman", slug: "salaryman" },
  { name: "Samurai", slug: "samurai" },
  { name: "Satire", slug: "satire" },
  { name: "Saving the World", slug: "saving-the-world" },
  { name: "Scheming", slug: "scheming" },
  { name: "Schizophrenia", slug: "schizophrenia" },
  { name: "Scientists", slug: "scientists" },
  { name: "Sculptors", slug: "sculptors" },
  { name: "Sealed Power", slug: "sealed-power" },
  { name: "Second Chance", slug: "second-chance" },
  { name: "Secret Crush", slug: "secret-crush" },
  { name: "Secret Identity", slug: "secret-identity" },
  { name: "Secret Organizations", slug: "secret-organizations" },
  { name: "Secret Relationship", slug: "secret-relationship" },
  { name: "Secretive Protagonist", slug: "secretive-protagonist" },
  { name: "Secrets", slug: "secrets" },
  { name: "Sect Development", slug: "sect-development" },
  { name: "Seduction", slug: "seduction" },
  { name: "Seeing Things Other Humans Can't", slug: "seeing-things-other-humans-cant" },
  { name: "Selfish Protagonist", slug: "selfish-protagonist" },
  { name: "Selfless Protagonist", slug: "selfless-protagonist" },
  { name: "Seme Protagonist", slug: "seme-protagonist" },
  { name: "Senpai-Kouhai Relationship", slug: "senpai-kouhai-relationship" },
  { name: "Sentient Objects", slug: "sentient-objects" },
  { name: "Sentimental Protagonist", slug: "sentimental-protagonist" },
  { name: "Serial Killers", slug: "serial-killers" },
  { name: "Servants", slug: "servants" },
  { name: "Seven Deadly Sins", slug: "seven-deadly-sins" },
  { name: "Seven Virtues", slug: "seven-virtues" },
  { name: "Sex Friends", slug: "sex-friends" },
  { name: "Sexual Abuse", slug: "sexual-abuse" },
  { name: "Sexual Cultivation Technique", slug: "sexual-cultivation-technique" },
  { name: "Shameless Protagonist", slug: "shameless-protagonist" },
  { name: "Shapeshifters", slug: "shapeshifters" },
  { name: "Sharing A Body", slug: "sharing-a-body" },
  { name: "Sharp-tongued Characters", slug: "sharp-tongued-characters" },
  { name: "Shield User", slug: "shield-user" },
  { name: "Shikigami", slug: "shikigami" },
  { name: "Short Story", slug: "short-story" },
  { name: "Shota", slug: "shota" },
  { name: "Showbiz", slug: "showbiz" },
  { name: "Shy Characters", slug: "shy-characters" },
  { name: "Sibling Rivalry", slug: "sibling-rivalry" },
  { name: "Siblings", slug: "siblings" },
  { name: "Siblings Care", slug: "siblings-care" },
  { name: "Siblings Not Related by Blood", slug: "siblings-not-related-by-blood" },
  { name: "Sickly Characters", slug: "sickly-characters" },
  { name: "Sign Language", slug: "sign-language" },
  { name: "Singers", slug: "singers" },
  { name: "Single Parent", slug: "single-parent" },
  { name: "Sister Complex", slug: "sister-complex" },
  { name: "Skill Assimilation", slug: "skill-assimilation" },
  { name: "Skill Books", slug: "skill-books" },
  { name: "Skill Creation", slug: "skill-creation" },
  { name: "Slave Harem", slug: "slave-harem" },
  { name: "Slave Protagonist", slug: "slave-protagonist" },
  { name: "Slaves", slug: "slaves" },
  { name: "Sleeping", slug: "sleeping" },
  { name: "Slow Growth at Start", slug: "slow-growth-at-start" },
  { name: "Slow Romance", slug: "slow-romance" },
  { name: "Smart Couple", slug: "smart-couple" },
  { name: "Social Outcasts", slug: "social-outcasts" },
  { name: "Soldiers", slug: "soldiers" },
  { name: "Soul Power", slug: "soul-power" },
  { name: "Souls", slug: "souls" },
  { name: "Spatial Manipulation", slug: "spatial-manipulation" },
  { name: "Spear Wielder", slug: "spear-wielder" },
  { name: "Special Abilities", slug: "special-abilities" },
  { name: "Special Forces", slug: "special-forces" },
  { name: "Spies", slug: "spies" },
  { name: "Spirit Advisor", slug: "spirit-advisor" },
  { name: "Spirit Users", slug: "spirit-users" },
  { name: "Spirits", slug: "spirits" },
  { name: "Stalkers", slug: "stalkers" },
  { name: "Stockholm Syndrome", slug: "stockholm-syndrome" },
  { name: "Stoic Characters", slug: "stoic-characters" },
  { name: "Store Owner", slug: "store-owner" },
  { name: "Straight Seme", slug: "straight-seme" },
  { name: "Straight Uke", slug: "straight-uke" },
  { name: "Strategic Battles", slug: "strategic-battles" },
  { name: "Strategist", slug: "strategist" },
  { name: "Strength-based Social Hierarchy", slug: "strength-based-social-hierarchy" },
  { name: "Strong Love Interests", slug: "strong-love-interests" },
  { name: "Strong to Stronger", slug: "strong-to-stronger" },
  { name: "Stubborn Protagonist", slug: "stubborn-protagonist" },
  { name: "Student Council", slug: "student-council" },
  { name: "Student-Teacher Relationship", slug: "student-teacher-relationship" },
  { name: "Subtle Romance", slug: "subtle-romance" },
  { name: "Succubus", slug: "succubus" },
  { name: "Sudden Strength Gain", slug: "sudden-strength-gain" },
  { name: "Sudden Wealth", slug: "sudden-wealth" },
  { name: "Suicides", slug: "suicides" },
  { name: "Summoned Hero", slug: "summoned-hero" },
  { name: "Summoning Magic", slug: "summoning-magic" },
  { name: "Superheroes", slug: "superheroes" },
  { name: "Survival", slug: "survival" },
  { name: "Survival Game", slug: "survival-game" },
  { name: "Sword And Magic", slug: "sword-and-magic" },
  { name: "Sword Wielder", slug: "sword-wielder" },
  { name: "System Administrator", slug: "system-administrator" },
  { name: "Teachers", slug: "teachers" },
  { name: "Teamwork", slug: "teamwork" },
  { name: "Technological Gap", slug: "technological-gap" },
  { name: "Tentacles", slug: "tentacles" },
  { name: "Terminal Illness", slug: "terminal-illness" },
  { name: "Terrorists", slug: "terrorists" },
  { name: "Thieves", slug: "thieves" },
  { name: "Threesome", slug: "threesome" },
  { name: "Thriller", slug: "thriller" },
  { name: "Time Loop", slug: "time-loop" },
  { name: "Time Manipulation", slug: "time-manipulation" },
  { name: "Time Paradox", slug: "time-paradox" },
  { name: "Time Skip", slug: "time-skip" },
  { name: "Time Travel", slug: "time-travel" },
  { name: "Timid Protagonist", slug: "timid-protagonist" },
  { name: "Tomboyish Female Lead", slug: "tomboyish-female-lead" },
  { name: "Torture", slug: "torture" },
  { name: "Toys", slug: "toys" },
  { name: "Tragic Past", slug: "tragic-past" },
  { name: "Transformation Ability", slug: "transformation-ability" },
  { name: "Transgender", slug: "transgender" },
  { name: "Transmigration", slug: "transmigration" },
  { name: "Transplanted Memories", slug: "transplanted-memories" },
  { name: "Transported into a Game World", slug: "transported-into-a-game-world" },
  { name: "Transported into Another World", slug: "transported-into-another-world" },
  { name: "Transported Modern Structure", slug: "transported-modern-structure" },
  { name: "Trap", slug: "trap" },
  { name: "Tribal Society", slug: "tribal-society" },
  { name: "Trickster", slug: "trickster" },
  { name: "Trolls", slug: "trolls" },
  { name: "Tsundere", slug: "tsundere" },
  { name: "Twins", slug: "twins" },
  { name: "Twisted Personality", slug: "twisted-personality" },
  { name: "Ugly Protagonist", slug: "ugly-protagonist" },
  { name: "Ugly to Beautiful", slug: "ugly-to-beautiful" },
  { name: "Unconditional Love", slug: "unconditional-love" },
  { name: "Underestimated Protagonist", slug: "underestimated-protagonist" },
  { name: "Unique Cultivation Technique", slug: "unique-cultivation-technique" },
  { name: "Unique Weapon User", slug: "unique-weapon-user" },
  { name: "Unique Weapons", slug: "unique-weapons" },
  { name: "Unlucky Protagonist", slug: "unlucky-protagonist" },
  { name: "Unreliable Narrator", slug: "unreliable-narrator" },
  { name: "Unrequited Love", slug: "unrequited-love" },
  { name: "Valkyries", slug: "valkyries" },
  { name: "Vampires", slug: "vampires" },
  { name: "Villainess Noble Girls", slug: "villainess-noble-girls" },
  { name: "Virtual Reality", slug: "virtual-reality" },
  { name: "Vocaloid", slug: "vocaloid" },
  { name: "Voice Actors", slug: "voice-actors" },
  { name: "Voyeurism", slug: "voyeurism" },
  { name: "Waiters", slug: "waiters" },
  { name: "War Records", slug: "war-records" },
  { name: "Wars", slug: "wars" },
  { name: "Weak Protagonist", slug: "weak-protagonist" },
  { name: "Weak to Strong", slug: "weak-to-strong" },
  { name: "Wealthy Characters", slug: "wealthy-characters" },
  { name: "Werebeasts", slug: "werebeasts" },
  { name: "Wishes", slug: "wishes" },
  { name: "Witches", slug: "witches" },
  { name: "Wizards", slug: "wizards" },
  { name: "World Hopping", slug: "world-hopping" },
  { name: "World Invasion", slug: "world-invasion" },
  { name: "World Travel", slug: "world-travel" },
  { name: "World Tree", slug: "world-tree" },
  { name: "Writers", slug: "writers" },
  { name: "Wuxia", slug: "wuxia" },
  { name: "Xianxia", slug: "xianxia" },
  { name: "Xuanhuan", slug: "xuanhuan" },
  { name: "Yandere", slug: "yandere" },
  { name: "Youkai", slug: "youkai" },
  { name: "Younger Brothers", slug: "younger-brothers" },
  { name: "Younger Love Interests", slug: "younger-love-interests" },
  { name: "Younger Sisters", slug: "younger-sisters" },
  { name: "Zombies", slug: "zombies" },
];
